### ISSUE TITLE
The future of the smart glasses.

### ISSUE THREAD

**Issue by SirEndii** [Seniorendi/AdvancedPeripherals#515]
### Describe your idea

The upcoming 0.8 update is set to bring a significant transformation to our AR Glasses, to the extent that I've entirely replaced the old system with a new one and rebranded them as Smart Glasses.

I'm initiating this issue request to establish a centralized place for discussing the forthcoming developments and desired features for these glasses.

Furthermore, to enhance the centralization of our Smart Glasses' future, I will compile a list of all presently open issues related to Smart Glasses/AR Goggles:

Features:
- [x] IntelligenceModding/Advanced-Peripherals-Features#26, SirEndii/Advanced-Peripherals-Features#50 More debug functions to retrieve more information about the player/the screen
- [x] IntelligenceModding/Advanced-Peripherals-Features#52 Player Events
- [ ] IntelligenceModding/Advanced-Peripherals-Features/issues/47 Player tracking
- [x] IntelligenceModding/Advanced-Peripherals-Features#53 Enhanced rendering functions like polygons
- [x] IntelligenceModding/Advanced-Peripherals-Features#57 3D Rendering
- [x] IntelligenceModding/Advanced-Peripherals-Features#13 Hotkeys
- [x] IntelligenceModding/Advanced-Peripherals-Features#59 A keyboard integrated as a module
- [x] Night Vision Module

Bugs (Since the old system is gone, these bugs should also be gone):
- There are currently no bugs that are tracked

The progress for the 0.8 update is also "documented" via the commits on GitHub →[Branch 0.8](https://github.com/SirEndii/AdvancedPeripherals/commits/dev/0.8/)

**Comment by PABessero** [comment]
About the coordinates system:

Will it be absolute (in world / MC coords)
or relative (either to the block the goggles are linked to, or the player that has the goggles)

Same question for the dimensions, at least for the AR part

**Comment by SirEndii** [comment]
> About the coordinates system:
> 
> Will it be absolute (in world / MC coords) or relative (either to the block the goggles are linked to, or the player that has the goggles)
> 
> Same question for the dimensions, at least for the AR part

Discussable

To retrieve player coords? Absolute and relative, the dimension would be an extra property you can retrieve from the glasses.
To retrieve coords from blocks/objects in the world? Also, probably both, but I would make it configurable to disable absolute coordinates 

Note that there isn't a block anymore. So all coordinates would be relative to the player's eye position
I am gonna post some pictures in a minute

**Comment by SirEndii** [comment]
small preview

The glasses with three peripherals and the overlay module:

![image](https://github.com/SirEndii/AdvancedPeripherals/assets/67484093/5cea01bb-53f6-4476-bc89-5e0191145277)


![image](https://github.com/SirEndii/AdvancedPeripherals/assets/67484093/3be6b0d8-18bd-472b-b2ef-44e8f56a9a07)

**Comment by zyxkad** [comment]
I want the glasses can render 3D blocks if possible, so we can use computer to make 3D games. It maybe have to create another dimension. If the works are to heavy for you then nvm.

**Comment by SirEndii** [comment]
That's a thing I will 99,9% add to the glasses. 🙂

**Comment by PalTheTaur** [comment]
For the 3D rendering, we would definitely need some way of rendering mass blocks instead of 1 by 1, though, the mention of 3D games by the person above, could maybe have a “VR mode” where it just is a whole different world and the computer is free to overwrite blocks and stuff, but that is definitely excessive.

**Comment by SirEndii** [comment]
Yeah, that's such a thing I want to discuss when I start making the feature
How players think the endpoint should look like

**Comment by zyxkad** [comment]
I opened an issue for it <https://github.com/SirEndii/Advanced-Peripherals-Features/issues/3>

**Comment by PalTheTaur** [comment]
hey for the GUI peripheral idea, even without letting a whole custom GUI maker exist, A preset GUI based on some common vanilla and modded GUIs with some button events, and something like the inventory API would be a good way to atleast have a basic version, but a custom GUI would be killer. 

Would also save me from having this janky thing I currently have set up in my world with ender chests mod.

**Comment by bmartin127** [comment]
will 1.18.2 have this new system?

**Comment by SirEndii** [comment]
@bmartin127 
If I have the motivation and time to backport this, yeah
I guess I will backport this, but I need to see how much work this acutally is.

**Comment by getkirill** [comment]
can't wait for smart glasses to be added :)

**Comment by SirEndii** [comment]
Finally got some time to work on the glasses
Got object syncing to the client done and basic rendering

(This is a YouTube video, you can click on it)

[![Watch the video](https://img.youtube.com/vi/_fSWUjhhweQ/maxresdefault.jpg)](https://youtu.be/_fSWUjhhweQ)

**Comment by SirEndii** [comment]
This is my current test script
It deletes the objects that were created before(from another script)
Creates two with some different sizes and colors
Waits a second and then changes the color and size of the objects for testing 

The objects are always in sync with the client. If one was updated via a function, it syncs the changes to the client and displays the change without deleting the old object and creating a new one. Essentially preventing flickering.

```lua
test = peripheral.wrap("back")

test.clear()
sleep(1)
panelOne = test.createPanel("one", {maxX = 160, maxY = 160})
panelTwo = test.createPanel("two", {opacity = 0.3, x = 500, y = 500, maxY = 40, maxX = 40, color = 0xFF8448})

sleep(1)
panelOne.setColor(0x003c9c)
panelTwo.setMaxX(300)
```

**Comment by nmgix** [comment]
Would be cool to get barebone version of goggles before 0.8, for sure it would ruin joy of full 0.8 release, but i would be happy even w/ only ability to draw basic shapes lol.
Anyway, good job keeping up the good work👍

**Comment by SirEndii** [comment]
Sure
I will try to publish a small preview of the documentation and a working 0.8 build
But note that I constantly change the api or add and remove features

**Comment by nmgix** [comment]
You are trying to scare me with ability to draw my full base on my goggles. The only question is what happened to that tool that gave ability to convert "paint" images (.nfp) to cc:t compatible? Didnt find source code as documentation is quite old

**Comment by awesomebossdj7** [comment]
are you going to add a entity sensor and a block scanner like plethora? you said you were planning on making smart glasses compatible with plethora scripts

**Comment by SirEndii** [comment]
I am unsure if I am even capable of adding plethora support
Currently everything is made from the ground up as a new api

The geo scanner will act as a block scanner since you can add peripherals to the glasses
And the environment detector can be used to detect entities

**Comment by SirEndii** [comment]
This is now tracked in the 0.8 backlog → https://github.com/orgs/IntelligenceModding/projects/6/views/1
I've set a deadline to a month which will hopefully push me or contributors to finish this

**Comment by abc123me** [comment]
Any updates on this? What branch is the 0.8 development taking place on? I'd like to fork and work on the development version so hopefully we can have it working for a modded server I play on.
